# Generated by Django 5.2.4 on 2025-07-24 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mascot', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(blank=True, to='draft_picks.player')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(choices=[('1', 'First Round'), ('2', 'Second Round'), ('3', 'Third Round')], default='1', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_picks.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_picks.team')),
            ],
            options={
                'ordering': ['pick'],
            },
        ),
    ]
